package wizard

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generateEnvFile(cfg *Config) error {
	var b strings.Builder

	b.WriteString("# Bot Army — generated by bot-army init\n\n")

	// Port map (for TUI and external tools to find services)
	b.WriteString("# Host ports (connect from outside Docker)\n")
	b.WriteString(fmt.Sprintf("STARTER_NATS_PORT=%s\n", cfg.Ports.NATS))
	b.WriteString(fmt.Sprintf("STARTER_NATS_MONITOR_PORT=%s\n", cfg.Ports.NATSMonitor))
	b.WriteString(fmt.Sprintf("STARTER_POSTGRES_PORT=%s\n", cfg.Ports.Postgres))
	b.WriteString(fmt.Sprintf("STARTER_OLLAMA_PORT=%s\n", cfg.Ports.Ollama))
	b.WriteString("\n")

	// Postgres (internal — bots use these inside Docker network)
	b.WriteString("# PostgreSQL (internal)\n")
	b.WriteString("POSTGRES_PASSWORD=postgres\n")
	b.WriteString("DATABASE_HOST=postgres\n")
	b.WriteString("DATABASE_PORT=5432\n")
	b.WriteString("DATABASE_USER=postgres\n")
	b.WriteString("DATABASE_PASSWORD=postgres\n\n")

	// NATS (internal)
	b.WriteString("# NATS (internal)\n")
	b.WriteString("NATS_HOST=nats\n")
	b.WriteString("NATS_PORT=4222\n\n")

	// LLM provider chain
	b.WriteString("# LLM\n")
	b.WriteString(fmt.Sprintf("BOT_ARMY_LLM_PROVIDER_CHAIN=%s\n", cfg.ProviderChain))

	// Provider-specific vars
	for _, p := range cfg.SelectedProviders {
		b.WriteString(fmt.Sprintf("\n# %s\n", p.Label))
		for _, ev := range p.EnvVars {
			val := cfg.EnvValues[ev.Key]
			if val == "" {
				val = ev.Default
			}
			if val != "" {
				b.WriteString(fmt.Sprintf("%s=%s\n", ev.Key, val))
			} else {
				b.WriteString(fmt.Sprintf("# %s=\n", ev.Key))
			}
		}
	}

	envPath := filepath.Join(cfg.InstallDir, ".env")
	if err := os.WriteFile(envPath, []byte(b.String()), 0o600); err != nil {
		return err
	}
	fmt.Printf("  ✓ .env\n")
	return nil
}

func generateComposeFile(cfg *Config) error {
	var b strings.Builder

	b.WriteString("# Bot Army — generated by bot-army init\n")
	b.WriteString("# Rebuild: docker compose up -d --build\n")
	b.WriteString("#\n")
	b.WriteString(fmt.Sprintf("# Host ports: NATS=%s  Monitor=%s  Postgres=%s  Ollama=%s\n",
		cfg.Ports.NATS, cfg.Ports.NATSMonitor, cfg.Ports.Postgres, cfg.Ports.Ollama))
	b.WriteString(fmt.Sprintf("# TUI connect: nats://localhost:%s\n\n", cfg.Ports.NATS))

	b.WriteString("services:\n")

	// NATS
	b.WriteString(fmt.Sprintf(`  nats:
    image: nats:2.10-alpine
    ports:
      - "%s:4222"
      - "%s:8222"
    command: ["--jetstream", "--http_port", "8222"]
    restart: unless-stopped

`, cfg.Ports.NATS, cfg.Ports.NATSMonitor))

	// Postgres
	needsDB := false
	for _, bot := range cfg.SelectedBots {
		if bot.NeedsDB {
			needsDB = true
			break
		}
	}
	if needsDB {
		b.WriteString(fmt.Sprintf(`  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "%s:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

`, cfg.Ports.Postgres))
	}

	// Ollama
	if cfg.SelfHostOllama {
		b.WriteString(fmt.Sprintf(`  ollama:
    image: ollama/ollama
    ports:
      - "%s:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

`, cfg.Ports.Ollama))
	}

	// Bots
	for _, bot := range cfg.SelectedBots {
		b.WriteString(fmt.Sprintf("  %s:\n", bot.ReleaseName))
		b.WriteString("    build:\n")
		b.WriteString("      context: ./repos\n")
		b.WriteString("      dockerfile: ../Dockerfile\n")
		b.WriteString("      args:\n")
		b.WriteString(fmt.Sprintf("        BOT_REPO: %s\n", bot.Repo))
		b.WriteString(fmt.Sprintf("        BOT_NAME: %s\n", bot.ReleaseName))
		b.WriteString("    env_file: .env\n")

		// Mounted volumes for log/PARA output
		b.WriteString("    volumes:\n")
		b.WriteString(fmt.Sprintf("      - ./data/logs/%s:/var/log/bot_army\n", bot.Name))

		deps := []string{"nats"}
		if bot.NeedsDB {
			deps = append(deps, "postgres")
		}
		if cfg.SelfHostOllama {
			deps = append(deps, "ollama")
		}
		b.WriteString("    depends_on:\n")
		for _, dep := range deps {
			if dep == "postgres" {
				b.WriteString(fmt.Sprintf("      %s:\n        condition: service_healthy\n", dep))
			} else {
				b.WriteString(fmt.Sprintf("      %s:\n        condition: service_started\n", dep))
			}
		}
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("\n")
	}

	// Volumes
	b.WriteString("volumes:\n")
	if needsDB {
		b.WriteString("  pgdata:\n")
	}
	if cfg.SelfHostOllama {
		b.WriteString("  ollama_data:\n")
	}

	composePath := filepath.Join(cfg.InstallDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  ✓ docker-compose.yml\n")
	return nil
}
