package wizard

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generateEnvFile(cfg *Config) error {
	var b strings.Builder

	b.WriteString("# Bot Army — generated by bot-army init\n\n")

	// Port map (for TUI and external tools to find services)
	b.WriteString("# Host ports (connect from outside Docker)\n")
	b.WriteString(fmt.Sprintf("STARTER_NATS_PORT=%s\n", cfg.Ports.NATS))
	b.WriteString(fmt.Sprintf("STARTER_NATS_MONITOR_PORT=%s\n", cfg.Ports.NATSMonitor))
	b.WriteString(fmt.Sprintf("STARTER_POSTGRES_PORT=%s\n", cfg.Ports.Postgres))
	b.WriteString(fmt.Sprintf("STARTER_OLLAMA_PORT=%s\n", cfg.Ports.Ollama))
	b.WriteString(fmt.Sprintf("STARTER_MCP_PORT=%s\n", cfg.Ports.MCP))
	if cfg.GitHubToken != "" {
		b.WriteString(fmt.Sprintf("STARTER_GITHUB_WEBHOOK_PORT=%s\n", cfg.Ports.GitHubWebhook))
	}
	b.WriteString("\n")

	// Postgres (internal — bots use these inside Docker network)
	b.WriteString("# PostgreSQL (internal)\n")
	b.WriteString("POSTGRES_PASSWORD=postgres\n")
	b.WriteString("DATABASE_HOST=postgres\n")
	b.WriteString("DATABASE_PORT=5432\n")
	b.WriteString("DATABASE_USER=postgres\n")
	b.WriteString("DATABASE_PASSWORD=postgres\n\n")

	// NATS (internal)
	b.WriteString("# NATS (internal)\n")
	b.WriteString("NATS_HOST=nats\n")
	b.WriteString("NATS_PORT=4222\n\n")

	// OpenTelemetry
	b.WriteString("# OpenTelemetry (optional, enabled if otelcol service is running)\n")
	b.WriteString("OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318\n\n")

	// LLM provider chain
	b.WriteString("# LLM\n")
	b.WriteString(fmt.Sprintf("BOT_ARMY_LLM_PROVIDER_CHAIN=%s\n", cfg.ProviderChain))

	// Integration flags
	b.WriteString("\n# Integration Flags (enabled based on selected bots)\n")
	for _, integ := range []string{"BRIDGE", "LLM", "PARA", "CONTEXT", "NOTIFICATION", "SYNAPSE", "DISPATCHER", "GTD"} {
		envVar := IntegrationToEnvVar(integ)
		enabled := cfg.EnabledIntegrations[integ]
		value := "false"
		if enabled {
			value = "true"
		}
		b.WriteString(fmt.Sprintf("%s=%s\n", envVar, value))
	}

	// Provider-specific vars
	for _, p := range cfg.SelectedProviders {
		b.WriteString(fmt.Sprintf("\n# %s\n", p.Label))
		for _, ev := range p.EnvVars {
			val := cfg.EnvValues[ev.Key]
			if val == "" {
				val = ev.Default
			}
			if val != "" {
				b.WriteString(fmt.Sprintf("%s=%s\n", ev.Key, val))
			} else {
				b.WriteString(fmt.Sprintf("# %s=\n", ev.Key))
			}
		}
	}

	// GitHub webhook integration (if configured)
	if cfg.GitHubToken != "" {
		b.WriteString("\n# GitHub webhook integration\n")
		b.WriteString(fmt.Sprintf("GITHUB_TOKEN=%s\n", cfg.GitHubToken))
		b.WriteString(fmt.Sprintf("GITHUB_WEBHOOK_SECRET=%s\n", cfg.GitHubWebhookSecret))
	}

	envPath := filepath.Join(cfg.InstallDir, ".env")
	if err := os.WriteFile(envPath, []byte(b.String()), 0o600); err != nil {
		return err
	}
	fmt.Printf("  ✓ .env\n")
	return nil
}

func generateComposeFile(cfg *Config) error {
	// Use pack-based compose when packs are selected
	if len(cfg.SelectedPacks) > 0 {
		// Generate database init script for all selected bots
		if err := generateDatabaseInitScript(cfg); err != nil {
			return err
		}
		// Generate OTLP collector config (optional)
		if err := generateOTelColConfig(cfg); err != nil {
			return err
		}
		return generatePackComposeFile(cfg)
	}
	return generateBotComposeFile(cfg)
}

func generateDatabaseInitScript(cfg *Config) error {
	// Collect all database names from selected bots
	dbSet := map[string]bool{}

	for _, pack := range cfg.SelectedPacks {
		for _, botName := range pack.Bots {
			for _, bot := range cfg.AllBots {
				if bot.Name == botName && bot.NeedsDB {
					// Convert bot name to database name (e.g. "gtd" -> "bot_army_gtd")
					dbName := "bot_army_" + bot.Name
					dbSet[dbName] = true
				}
			}
		}
	}

	if len(dbSet) == 0 {
		return nil // No databases needed
	}

	var b strings.Builder
	b.WriteString("-- Bot Army Database Initialization\n")
	b.WriteString("-- Auto-generated by bot-army init\n\n")

	for dbName := range dbSet {
		b.WriteString(fmt.Sprintf("CREATE DATABASE IF NOT EXISTS %s;\n", dbName))
	}

	initPath := filepath.Join(cfg.InstallDir, "init-databases.sql")
	if err := os.WriteFile(initPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  ✓ init-databases.sql\n")
	return nil
}

func generateOTelColConfig(cfg *Config) error {
	if !cfg.EnableOTLP {
		return nil // OTLP not enabled, skip config
	}

	config := `receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  logging:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
`

	configPath := filepath.Join(cfg.InstallDir, "otelcol.yaml")
	if err := os.WriteFile(configPath, []byte(config), 0o644); err != nil {
		return err
	}
	fmt.Printf("  ✓ otelcol.yaml\n")
	return nil
}

func generatePackComposeFile(cfg *Config) error {
	// Collect unique bot names from all selected packs for data dirs
	allBotNames := map[string]bool{}
	needsDB := len(cfg.SelectedPacks) > 0
	namedVols := map[string]bool{}
	for _, pack := range cfg.SelectedPacks {
		// Look up bot details for each bot in the pack
		for _, botName := range pack.Bots {
			allBotNames[botName] = true
			for _, bot := range cfg.AllBots {
				if bot.Name == botName && bot.NeedsDB {
					needsDB = true
				}
			}
		}
	}

	// Create data directories
	dataDirs := []string{"logs", "para", "state"}
	for _, dir := range dataDirs {
		dirPath := filepath.Join(cfg.InstallDir, "data", dir)
		os.MkdirAll(dirPath, 0o755)
		for name := range allBotNames {
			os.MkdirAll(filepath.Join(dirPath, name), 0o755)
		}
	}

	// Create host directories for bind-mount volumes (skip named volumes like "data:/path")
	for _, pack := range cfg.SelectedPacks {
		for _, botName := range pack.Bots {
			for _, bot := range cfg.AllBots {
				if bot.Name == botName {
					for _, vol := range bot.Volumes {
						parts := strings.SplitN(vol, ":", 2)
						if len(parts) == 2 && strings.HasPrefix(parts[0], "./") {
							hostPath := filepath.Join(cfg.InstallDir, parts[0])
							os.MkdirAll(hostPath, 0o755)
						}
					}
				}
			}
		}
	}

	var b strings.Builder

	b.WriteString("# Bot Army — generated by bot-army init (pack mode)\n")
	b.WriteString("# Rebuild: docker compose up -d --build\n")
	b.WriteString("# NOTE: Run docker compose commands from the directory containing this file\n")
	b.WriteString("#\n")
	b.WriteString(fmt.Sprintf("# Host ports: NATS=%s  Monitor=%s  Postgres=%s  Ollama=%s",
		cfg.Ports.NATS, cfg.Ports.NATSMonitor, cfg.Ports.Postgres, cfg.Ports.Ollama))
	if cfg.GitHubToken != "" {
		b.WriteString(fmt.Sprintf("  GitHub=%s", cfg.Ports.GitHubWebhook))
	}
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("# TUI connect: nats://localhost:%s\n\n", cfg.Ports.NATS))

	b.WriteString("services:\n")

	// NATS
	b.WriteString(fmt.Sprintf(`  nats:
    image: nats:2.10-alpine
    ports:
      - "%s:4222"
      - "%s:8222"
    command: ["--jetstream", "--http_port", "8222"]
    restart: unless-stopped

`, cfg.Ports.NATS, cfg.Ports.NATSMonitor))

	// Postgres (all packs share one DB server)
	if needsDB {
		b.WriteString(fmt.Sprintf(`  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "%s:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/00-init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

`, cfg.Ports.Postgres))
	}

	// Ollama
	if cfg.SelfHostOllama {
		b.WriteString(fmt.Sprintf(`  ollama:
    image: ollama/ollama
    ports:
      - "%s:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

`, cfg.Ports.Ollama))
	}

	// OpenTelemetry Collector (optional, defaults to enabled)
	if cfg.EnableOTLP {
		b.WriteString(`  otelcol:
    image: otel/opentelemetry-collector-contrib:0.103.0
    ports:
      - "4318:4318"
      - "4317:4317"
    volumes:
      - ./otelcol.yaml:/etc/otelcol-contrib/config.yaml
    restart: unless-stopped

`)
	}

	// Pack services — one container per pack, single BEAM VM
	for _, pack := range cfg.SelectedPacks {
		if pack.Name == "development" {
			continue // development pack has no services
		}

		b.WriteString(fmt.Sprintf("  %s:\n", pack.ReleaseName))
		b.WriteString("    build:\n")
		b.WriteString("      context: ./repos\n")
		b.WriteString("      dockerfile: ../Dockerfile.pack\n")
		b.WriteString("      args:\n")
		b.WriteString(fmt.Sprintf("        PACK_NAME: %s\n", pack.ReleaseName))
		b.WriteString(fmt.Sprintf("        PACK_REPO: ergon-pack-%s\n", pack.Name))
		b.WriteString("    env_file: .env\n")
		// Check for services that need port mappings
		hasMCP := false
		hasGitHub := false
		for _, botName := range pack.Bots {
			if botName == "surface_mcp" {
				hasMCP = true
			}
			if botName == "github" && cfg.GitHubToken != "" {
				hasGitHub = true
			}
		}
		if hasMCP || hasGitHub {
			b.WriteString("    ports:\n")
			if hasMCP {
				b.WriteString(fmt.Sprintf("      - \"%s:39900\"\n", cfg.Ports.MCP))
			}
			if hasGitHub {
				b.WriteString(fmt.Sprintf("      - \"%s:39904\"\n", cfg.Ports.GitHubWebhook))
			}
		}
		b.WriteString("    environment:\n")
		b.WriteString("      PACK_MODE: \"true\"\n")

		// Volume mounts for all bots in the pack (named volumes for portability)
		b.WriteString("    volumes:\n")
		b.WriteString(fmt.Sprintf("      - logs_%s:/var/log/bot_army\n", pack.ReleaseName))
		b.WriteString("      - para:/opt/app/para\n")
		b.WriteString("      - state:/opt/app/state\n")

		// Custom volume mounts from bot catalog (deduplicated per pack)
		seenVols := map[string]bool{}
		for _, botName := range pack.Bots {
			for _, bot := range cfg.AllBots {
				if bot.Name == botName {
					for _, vol := range bot.Volumes {
						if !seenVols[vol] {
							b.WriteString(fmt.Sprintf("      - %s\n", vol))
							seenVols[vol] = true
							// Track named volumes for the volumes: section
							parts := strings.SplitN(vol, ":", 2)
							if len(parts) == 2 && !strings.HasPrefix(parts[0], "./") && !strings.HasPrefix(parts[0], "/") {
								namedVols[parts[0]] = true
							}
						}
					}
				}
			}
		}

		// Dependencies
		deps := []string{"nats"}
		if needsDB {
			deps = append(deps, "postgres")
		}
		if cfg.SelfHostOllama {
			deps = append(deps, "ollama")
		}
		b.WriteString("    depends_on:\n")
		for _, dep := range deps {
			if dep == "postgres" {
				b.WriteString(fmt.Sprintf("      %s:\n        condition: service_healthy\n", dep))
			} else {
				b.WriteString(fmt.Sprintf("      %s:\n        condition: service_started\n", dep))
			}
		}
		b.WriteString("    restart: unless-stopped\n\n")
	}

	// Custom bots (still per-bot)
	for _, customBot := range cfg.CustomBots {
		b.WriteString(fmt.Sprintf("  %s:\n", customBot.ReleaseName))
		b.WriteString("    build:\n")
		b.WriteString("      context: ./repos\n")
		b.WriteString("      dockerfile: ../Dockerfile\n")
		b.WriteString("      args:\n")
		b.WriteString(fmt.Sprintf("        BOT_REPO: %s\n", customBot.Name))
		b.WriteString(fmt.Sprintf("        BOT_NAME: %s\n", customBot.ReleaseName))
		b.WriteString("    env_file: .env\n")

		if len(customBot.EnvVars) > 0 {
			b.WriteString("    environment:\n")
			for k, v := range customBot.EnvVars {
				b.WriteString(fmt.Sprintf("      %s: %s\n", k, v))
			}
		}

		b.WriteString("    volumes:\n")
		b.WriteString(fmt.Sprintf("      - logs_%s:/var/log/bot_army\n", customBot.Name))
		b.WriteString("      - para:/opt/app/para\n")
		b.WriteString("      - state:/opt/app/state\n")

		for _, mount := range cfg.CustomMounts {
			b.WriteString(fmt.Sprintf("      - %s:%s\n", mount.Source, mount.Destination))
		}

		b.WriteString("    depends_on:\n")
		b.WriteString("      nats:\n")
		b.WriteString("        condition: service_started\n")
		b.WriteString("    restart: unless-stopped\n\n")
	}

	// Volumes
	b.WriteString("volumes:\n")
	for _, pack := range cfg.SelectedPacks {
		if pack.Name == "development" {
			continue
		}
		b.WriteString(fmt.Sprintf("  logs_%s:\n", pack.ReleaseName))
	}
	for _, customBot := range cfg.CustomBots {
		b.WriteString(fmt.Sprintf("  logs_%s:\n", customBot.Name))
	}
	b.WriteString("  para:\n")
	b.WriteString("  state:\n")
	if needsDB {
		b.WriteString("  pgdata:\n")
	}
	if cfg.SelfHostOllama {
		b.WriteString("  ollama_data:\n")
	}
	// Named volumes from bot catalog entries (e.g. graphify_cache_data, internal_docs_crawl)
	for volName := range namedVols {
		b.WriteString(fmt.Sprintf("  %s:\n", volName))
	}

	composePath := filepath.Join(cfg.InstallDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  ✓ docker-compose.yml (pack mode)\n")
	return nil
}

func generateBotComposeFile(cfg *Config) error {
	// Create necessary data directories for volumes
	dataDirs := []string{"logs", "para", "state"}
	for _, dir := range dataDirs {
		dirPath := filepath.Join(cfg.InstallDir, "data", dir)
		os.MkdirAll(dirPath, 0o755)
		for _, bot := range cfg.SelectedBots {
			botPath := filepath.Join(dirPath, bot.Name)
			os.MkdirAll(botPath, 0o755)
		}
	}

	// Create host directories for bind-mount volumes (skip named volumes like "data:/path")
	for _, bot := range cfg.SelectedBots {
		for _, vol := range bot.Volumes {
			parts := strings.SplitN(vol, ":", 2)
			if len(parts) == 2 && strings.HasPrefix(parts[0], "./") {
				hostPath := filepath.Join(cfg.InstallDir, parts[0])
				os.MkdirAll(hostPath, 0o755)
			}
		}
	}

	var b strings.Builder

	b.WriteString("# Bot Army — generated by bot-army init\n")
	b.WriteString("# Rebuild: docker compose up -d --build\n")
	b.WriteString("#\n")
	b.WriteString(fmt.Sprintf("# Host ports: NATS=%s  Monitor=%s  Postgres=%s  Ollama=%s\n",
		cfg.Ports.NATS, cfg.Ports.NATSMonitor, cfg.Ports.Postgres, cfg.Ports.Ollama))
	b.WriteString(fmt.Sprintf("# TUI connect: nats://localhost:%s\n\n", cfg.Ports.NATS))

	b.WriteString("services:\n")

	b.WriteString(fmt.Sprintf(`  nats:
    image: nats:2.10-alpine
    ports:
      - "%s:4222"
      - "%s:8222"
    command: ["--jetstream", "--http_port", "8222"]
    restart: unless-stopped

`, cfg.Ports.NATS, cfg.Ports.NATSMonitor))

	// Postgres
	needsDB := false
	for _, bot := range cfg.SelectedBots {
		if bot.NeedsDB {
			needsDB = true
			break
		}
	}
	if needsDB {
		b.WriteString(fmt.Sprintf(`  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "%s:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

`, cfg.Ports.Postgres))
	}

	// Ollama
	if cfg.SelfHostOllama {
		b.WriteString(fmt.Sprintf(`  ollama:
    image: ollama/ollama
    ports:
      - "%s:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

`, cfg.Ports.Ollama))
	}

	// Collect named volumes from bot catalog entries for the volumes: section
	namedVols := map[string]bool{}

	// Bots (skip libraries — they're path deps bundled into each bot's release)
	for _, bot := range cfg.SelectedBots {
		if strings.HasPrefix(bot.Repo, "bot_army_library_") {
			continue
		}
		b.WriteString(fmt.Sprintf("  %s:\n", bot.ReleaseName))
		b.WriteString("    build:\n")
		b.WriteString("      context: ./repos\n")
		b.WriteString("      dockerfile: ../Dockerfile\n")
		b.WriteString("      args:\n")
		b.WriteString(fmt.Sprintf("        BOT_REPO: %s\n", bot.Repo))
		b.WriteString(fmt.Sprintf("        BOT_NAME: %s\n", bot.ReleaseName))
		b.WriteString("    env_file: .env\n")
		if bot.Name == "surface_mcp" {
			b.WriteString("    ports:\n")
			b.WriteString(fmt.Sprintf("      - \"%s:39900\"\n", cfg.Ports.MCP))
		}

		// Mounted volumes for log/PARA output and persistent data
		b.WriteString("    volumes:\n")
		b.WriteString(fmt.Sprintf("      - logs_%s:/var/log/bot_army\n", bot.Name))
		b.WriteString("      - para:/opt/app/para\n")
		b.WriteString("      - state:/opt/app/state\n")

		// Custom volume mounts from bot catalog
		for _, vol := range bot.Volumes {
			b.WriteString(fmt.Sprintf("      - %s\n", vol))
			// Track named volumes (no "./" or "/" prefix)
			parts := strings.SplitN(vol, ":", 2)
			if len(parts) == 2 && !strings.HasPrefix(parts[0], "./") && !strings.HasPrefix(parts[0], "/") {
				namedVols[parts[0]] = true
			}
		}

		// Development mode: mount library repos for live editing
		if cfg.DevMode {
			b.WriteString("      # Library mounts for development\n")
			b.WriteString("      - ./repos/bot_army_library_runtime:/app/deps/bot_army_library_runtime\n")
			b.WriteString("      - ./repos/bot_army_library_core:/app/deps/bot_army_library_core\n")
			b.WriteString("      - ./repos/bot_army_library_learning:/app/deps/bot_army_library_learning\n")
		}

		deps := []string{"nats"}
		if bot.NeedsDB {
			deps = append(deps, "postgres")
		}
		if cfg.SelfHostOllama {
			deps = append(deps, "ollama")
		}
		b.WriteString("    depends_on:\n")
		for _, dep := range deps {
			if dep == "postgres" {
				b.WriteString(fmt.Sprintf("      %s:\n        condition: service_healthy\n", dep))
			} else {
				b.WriteString(fmt.Sprintf("      %s:\n        condition: service_started\n", dep))
			}
		}
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("\n")
	}

	// Custom bots
	for _, customBot := range cfg.CustomBots {
		b.WriteString(fmt.Sprintf("  %s:\n", customBot.ReleaseName))
		b.WriteString("    build:\n")
		b.WriteString("      context: ./repos\n")
		b.WriteString("      dockerfile: ../Dockerfile\n")
		b.WriteString("      args:\n")
		b.WriteString(fmt.Sprintf("        BOT_REPO: %s\n", customBot.Name))
		b.WriteString(fmt.Sprintf("        BOT_NAME: %s\n", customBot.ReleaseName))
		b.WriteString("    env_file: .env\n")

		// Custom env vars for this bot
		if len(customBot.EnvVars) > 0 {
			b.WriteString("    environment:\n")
			for k, v := range customBot.EnvVars {
				b.WriteString(fmt.Sprintf("      %s: %s\n", k, v))
			}
		}

		// Standard volumes
		b.WriteString("    volumes:\n")
		b.WriteString(fmt.Sprintf("      - logs_%s:/var/log/bot_army\n", customBot.Name))
		b.WriteString("      - para:/opt/app/para\n")
		b.WriteString("      - state:/opt/app/state\n")

		// Custom mounts
		for _, mount := range cfg.CustomMounts {
			b.WriteString(fmt.Sprintf("      - %s:%s\n", mount.Source, mount.Destination))
		}

		b.WriteString("    depends_on:\n")
		b.WriteString("      nats:\n")
		b.WriteString("        condition: service_started\n")
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("\n")
	}

	// Volumes
	b.WriteString("volumes:\n")
	for _, bot := range cfg.SelectedBots {
		if strings.HasPrefix(bot.Repo, "bot_army_library_") {
			continue
		}
		b.WriteString(fmt.Sprintf("  logs_%s:\n", bot.Name))
	}
	for _, customBot := range cfg.CustomBots {
		b.WriteString(fmt.Sprintf("  logs_%s:\n", customBot.Name))
	}
	b.WriteString("  para:\n")
	b.WriteString("  state:\n")
	if needsDB {
		b.WriteString("  pgdata:\n")
	}
	if cfg.SelfHostOllama {
		b.WriteString("  ollama_data:\n")
	}
	// Named volumes from bot catalog entries (e.g. graphify_cache_data, internal_docs_crawl)
	for volName := range namedVols {
		b.WriteString(fmt.Sprintf("  %s:\n", volName))
	}

	composePath := filepath.Join(cfg.InstallDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  ✓ docker-compose.yml\n")
	return nil
}
