#!/bin/bash
# Headless quickstart: core bots + Ollama, no interactive prompts.
# For the interactive version, use `make quickstart` instead.
#
# Override host ports via env:
#   NATS_HOST_PORT=4222 POSTGRES_HOST_PORT=5432 ./scripts/quickstart-default.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

CATALOG="catalog/bots.json"
if [ ! -f "$CATALOG" ]; then
  echo "Error: $CATALOG not found — run 'make sync' first" >&2
  exit 1
fi

GIT_ORG="ergon-automation-labs"

# Host ports — high defaults to avoid collisions with local services
NATS_HOST_PORT="${NATS_HOST_PORT:-54222}"
NATS_MONITOR_HOST_PORT="${NATS_MONITOR_HOST_PORT:-58222}"
POSTGRES_HOST_PORT="${POSTGRES_HOST_PORT:-55432}"
OLLAMA_HOST_PORT="${OLLAMA_HOST_PORT:-51434}"
MCP_HOST_PORT="${MCP_HOST_PORT:-39900}"

# Select core bots from catalog
# Output: remote repo_name release_name bot_name needs_db
core_bots=$(python3 -c "
import json
bots = json.load(open('$CATALOG'))
for b in bots:
    if b['category'] == 'core':
        remote = b.get('remote', b['repo'])
        print(remote, b['repo'], b['release_name'], b['name'], str(b.get('needs_db', False)).lower())
")

echo "Cloning core bot repos..."
mkdir -p repos
cat > repos/.dockerignore << 'DOCKERIGNORE'
**/deps
**/_build
**/.git
**/.elixir_ls
**/doc
**/test
**/*.beam
**/*.ez
DOCKERIGNORE

# Clone library repos (remote names differ from local dir names)
declare -A lib_remotes=(
  ["bot_army_runtime"]="ergon-library-runtime"
  ["bot_army_core"]="ergon-library-core"
  ["bot_army_learning"]="ergon-library-learning"
)
for lib in "${!lib_remotes[@]}"; do
  remote="${lib_remotes[$lib]}"
  dest="repos/$lib"
  if [ ! -d "$dest" ]; then
    echo "  ⏳ $remote..."
    if git clone --depth 1 "https://github.com/${GIT_ORG}/${remote}.git" "$dest" 2>&1; then
      echo "  ✓ $remote"
    else
      echo "  ✗ $remote (clone failed)" >&2
      exit 1
    fi
  else
    echo "  ✓ $remote (exists)"
  fi
done

needs_db=false
bot_services=""

while IFS=' ' read -r remote repo release bot_name db_flag; do
  [ -z "$repo" ] && continue

  dest="repos/$repo"
  if [ ! -d "$dest" ]; then
    echo "  ⏳ $remote..."
    if git clone --depth 1 "https://github.com/${GIT_ORG}/${remote}.git" "$dest" 2>&1; then
      echo "  ✓ $remote"
    else
      echo "  ✗ $remote (clone failed)" >&2
      exit 1
    fi
  else
    echo "  ✓ $remote (exists)"
  fi

  [ "$db_flag" = "true" ] && needs_db=true

  dep_block="      nats:\n        condition: service_started"
  if [ "$db_flag" = "true" ]; then
    dep_block="$dep_block\n      postgres:\n        condition: service_healthy"
  fi
  dep_block="$dep_block\n      ollama:\n        condition: service_started"

  bot_services+="
  ${release}:
    build:
      context: ./repos
      dockerfile: ../Dockerfile
      args:
        BOT_NAME: ${release}
        BOT_REPO: ${repo}
    env_file: .env
    volumes:
      - ./data/logs/${bot_name}:/var/log/bot_army
    depends_on:
$(echo -e "$dep_block")
    restart: unless-stopped
"
done <<< "$core_bots"

# Create data directories
mkdir -p data/logs data/para data/backups

echo ""
echo "Generating .env..."
cat > .env << ENVEOF
# Bot Army — generated by quickstart-default
# Edit this file to add API keys or change models.

# Host ports (connect from outside Docker)
STARTER_NATS_PORT=${NATS_HOST_PORT}
STARTER_NATS_MONITOR_PORT=${NATS_MONITOR_HOST_PORT}
STARTER_POSTGRES_PORT=${POSTGRES_HOST_PORT}
STARTER_OLLAMA_PORT=${OLLAMA_HOST_PORT}
STARTER_MCP_PORT=${MCP_HOST_PORT}

# PostgreSQL (internal — bots use these inside Docker)
POSTGRES_PASSWORD=postgres
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_USER=postgres
DATABASE_PASSWORD=postgres

# NATS (internal)
NATS_HOST=nats
NATS_PORT=4222

# LLM — Ollama (local)
BOT_ARMY_LLM_PROVIDER_CHAIN=ollama
OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_MODEL_LIGHT=llama3.1
OLLAMA_MODEL_MEDIUM=llama3.1
ENVEOF
echo "  ✓ .env"

echo "Generating docker-compose.yml..."
cat > docker-compose.yml << COMPEOF
# Bot Army — generated by quickstart-default
# Rebuild: docker compose up -d --build
#
# Host ports: NATS=${NATS_HOST_PORT}  Monitor=${NATS_MONITOR_HOST_PORT}  Postgres=${POSTGRES_HOST_PORT}  Ollama=${OLLAMA_HOST_PORT}  MCP=${MCP_HOST_PORT}
# TUI connect: nats://localhost:${NATS_HOST_PORT}
# Claude Desktop MCP: http://localhost:${MCP_HOST_PORT}/mcp

services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "${NATS_HOST_PORT}:4222"
      - "${NATS_MONITOR_HOST_PORT}:8222"
    command: ["--jetstream", "--http_port", "8222"]
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    ports:
      - "${OLLAMA_HOST_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  mcp:
    build:
      context: ./repos
      dockerfile: ../Dockerfile
      args:
        BOT_NAME: elixir_tools_mcp_bot
        BOT_REPO: bot_army_elixir_tools_mcp
    env_file: .env
    environment:
      MCP_PORT: "39900"
      MCP_TRANSPORT: "http"
      NATS_SERVERS: "nats:4222"
    ports:
      - "${MCP_HOST_PORT}:39900"
    depends_on:
      nats:
        condition: service_started
    restart: unless-stopped
${bot_services}
volumes:
  pgdata:
  ollama_data:
COMPEOF
echo "  ✓ docker-compose.yml"

bot_count=$(echo "$core_bots" | grep -c '.' || true)
echo ""
echo "✓ Configured ${bot_count} core bots + NATS + PostgreSQL + Ollama"
echo ""
echo "Port map:"
echo "  NATS:      localhost:${NATS_HOST_PORT}  (internal 4222)"
echo "  Monitor:   localhost:${NATS_MONITOR_HOST_PORT}  (internal 8222)"
echo "  Postgres:  localhost:${POSTGRES_HOST_PORT}  (internal 5432)"
echo "  Ollama:    localhost:${OLLAMA_HOST_PORT}  (internal 11434)"
echo "  MCP:       localhost:${MCP_HOST_PORT}  (internal 39900)"
echo ""
echo "Data directories:"
echo "  ./data/logs/     Bot logs (mounted from containers)"
echo "  ./data/para/     PARA output (mount to para_bot)"
echo "  ./data/backups/  DB backups (mount to backup_bot)"
echo ""
echo "To build and start:"
echo "  DOCKER_BUILDKIT=1 docker compose up -d --build"
